set -g prefix C-s

set -g default-terminal "xterm-256color"
set -ga terminal-overrides "xterm-256color"

set -g base-index 1

bind-key -n C-H resize-pane -L 5
bind-key -n C-J resize-pane -D 5
bind-key -n C-K resize-pane -U 5
bind-key -n C-L resize-pane -R 5

set -g status-right ""
set -g window-status-current-format "#[fg=green,bg=black] #I:#W "
set -g window-status-format "#[fg=black,bg=green] #I:#W "
set -g mode-keys vi
